cluster:
  name: cluster1
  id: 1

kubeProxyReplacement: true
k8sServiceHost: mesh1-control-plane
k8sServicePort: 6443

routingMode: native
autoDirectNodeRoutes: true
ipv4NativeRoutingCIDR: "10.0.0.0/8"

ipam:
  mode: kubernetes

image:
  pullPolicy: IfNotPresent

hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true
