## lbsvc.yaml
apiVersion: v1
kind: Service
metadata:
  name: test-lb
  labels:
    bgp: blue
spec:
  type: LoadBalancer
  trafficDistribution: PreferSameNode
  ports:
  - port: 80
    targetPort: 9898
    protocol: TCP
    name: http
  selector:
    svc: test-lb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
spec:
  replicas: 3
  selector:
    matchLabels:
      svc: test-lb
  template:
    metadata:
      labels:
        svc: test-lb
    spec:
      containers:
      - name: podinfo
        image: stefanprodan/podinfo:6.11.2
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 9898
        readinessProbe:
          httpGet:
            path: /readyz
            port: http
